Convert hook language to python
So that users can define their selected uv version, using "additional_dependencies"

It seems the hook fails with

> error: Failed to init hooks
>  caused by: Invalid hook `uv-lock-check`
>  caused by: Hook specified `additional_dependencies: uv==0.9.18` but the language `system` does not install an environment

when pyproject.toml file is not present but additional_dependencies given